apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Ensure data is not deleted when PV is released
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0f66f4cefe3fc4d2c
    fsType: ext4